using System.Globalization;
using System.Text;
using CrmLstg.Core.Configuration;
using CrmLstg.Core.Naming;
using Microsoft.Xrm.Sdk.Metadata;

namespace CrmLstg.Core.Generation;

public sealed class CSharpCodeGenerator
{
    private readonly GeneratorOptions _options;
    private readonly CSharpTypeMapper _typeMapper;

    public CSharpCodeGenerator(GeneratorOptions options)
    {
        _options = options;
        _typeMapper = new CSharpTypeMapper(options.UseSdkTypes);
    }

    public string GenerateEntityFile(EntityMetadata entity)
    {
        var className = CSharpIdentifierHelper.ToClassName(entity.LogicalName);
        var builder = new StringBuilder();

        AppendFileHeader(builder);
        builder.AppendLine($"namespace {_options.Namespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Strong types for {entity.LogicalName}.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public static partial class {className}");
        builder.AppendLine("{");
        builder.AppendLine($"    public const string EntityLogicalName = \"{entity.LogicalName}\";");
        builder.AppendLine($"    public const string EntitySetName = \"{entity.EntitySetName}\";");
        builder.AppendLine($"    public const int EntityTypeCode = {entity.ObjectTypeCode?.ToString(CultureInfo.InvariantCulture) ?? "0"};");
        builder.AppendLine();
        AppendFieldsClass(builder, entity);
        builder.AppendLine();

        if (_options.GenerateOptionSetEnums)
        {
            AppendOptionSetEnums(builder, entity, className);
        }

        builder.AppendLine($"    public sealed class Record");
        builder.AppendLine("    {");

        foreach (var attribute in GetOrderedAttributes(entity, _options.IncludeVirtualAttributes))
        {
            var propertyName = CSharpIdentifierHelper.ToPascalCaseIdentifier(attribute.LogicalName);
            var propertyType = _typeMapper.MapAttributeType(attribute);

            builder.AppendLine($"        public {propertyType} {propertyName} {{ get; set; }}");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    public string GenerateGlobalOptionSetFile(string enumName, OptionSetMetadataBase optionSet)
    {
        var builder = new StringBuilder();

        AppendFileHeader(builder);
        builder.AppendLine($"namespace {_options.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"public enum {enumName}");
        builder.AppendLine("{");

        if (optionSet is OptionSetMetadata localOptionSet)
        {
            foreach (var option in localOptionSet.Options.OrderBy(o => o.Value))
            {
                var memberName = CSharpIdentifierHelper.ToEnumMemberName(option.Label?.UserLocalizedLabel?.Label ?? string.Empty, option.Value ?? 0);
                builder.AppendLine($"    {memberName} = {option.Value},");
            }
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendFileHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by CrmLstg (CRM Dynamics late-bound strong types generator).");
        builder.AppendLine($"// Generated at {DateTime.UtcNow:O}");
        builder.AppendLine();
    }

    private void AppendFieldsClass(StringBuilder builder, EntityMetadata entity)
    {
        builder.AppendLine("    public static class Fields");
        builder.AppendLine("    {");

        foreach (var attribute in GetOrderedAttributes(entity, _options.IncludeVirtualAttributes))
        {
            var constantName = CSharpIdentifierHelper.ToFieldConstantName(attribute.LogicalName);
            builder.AppendLine($"        public const string {constantName} = \"{attribute.LogicalName}\";");
        }

        builder.AppendLine("    }");
    }

    private void AppendOptionSetEnums(StringBuilder builder, EntityMetadata entity, string className)
    {
        var attributes = GetOrderedAttributes(entity, _options.IncludeVirtualAttributes)
            .Where(_typeMapper.IsOptionSet)
            .ToList();

        if (attributes.Count == 0)
        {
            return;
        }

        builder.AppendLine("    public static class OptionSets");
        builder.AppendLine("    {");

        foreach (var attribute in attributes)
        {
            if (attribute is not EnumAttributeMetadata enumAttribute || enumAttribute.OptionSet == null)
            {
                continue;
            }

            var enumName = CSharpIdentifierHelper.ToPascalCaseIdentifier(attribute.LogicalName);

            builder.AppendLine($"        public enum {enumName}");
            builder.AppendLine("        {");

            if (enumAttribute.OptionSet is OptionSetMetadata optionSet)
            {
                foreach (var option in optionSet.Options.OrderBy(o => o.Value))
                {
                    var memberName = CSharpIdentifierHelper.ToEnumMemberName(
                        option.Label?.UserLocalizedLabel?.Label ?? string.Empty,
                        option.Value ?? 0);

                    builder.AppendLine($"            {memberName} = {option.Value},");
                }
            }

            builder.AppendLine("        }");
            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static IEnumerable<AttributeMetadata> GetOrderedAttributes(EntityMetadata entity, bool includeVirtualAttributes)
    {
        return entity.Attributes?
            .Where(attribute => (includeVirtualAttributes || attribute.AttributeType != AttributeTypeCode.Virtual)
                && (attribute.IsValidForCreate == true
                    || attribute.IsValidForUpdate == true
                    || attribute.IsValidForRead == true
                    || attribute.IsPrimaryId == true))
            .OrderBy(attribute => attribute.LogicalName, StringComparer.OrdinalIgnoreCase)
            ?? Enumerable.Empty<AttributeMetadata>();
    }
}
