using CrmLstg.Core.Configuration;
using CrmLstg.Core.IO;
using CrmLstg.Core.Metadata;
using Microsoft.PowerPlatform.Dataverse.Client;
using Microsoft.Xrm.Sdk;

namespace CrmLstg.Core.Generation;

public sealed class TypeGenerationService
{
    private readonly GeneratorOptions _options;

    public TypeGenerationService(GeneratorOptions options)
    {
        _options = options;
    }

    public async Task<GenerationResult> GenerateAsync(CancellationToken cancellationToken = default)
    {
        ValidateOptions();

        using var serviceClient = new ServiceClient(_options.ConnectionString);

        if (!serviceClient.IsReady)
        {
            throw new InvalidOperationException($"Failed to connect to Dataverse: {serviceClient.LastError}");
        }

        IOrganizationService organizationService = serviceClient;
        var solutionResolver = new SolutionEntityResolver(organizationService);
        var metadataProvider = new EntityMetadataProvider(organizationService);
        var codeGenerator = new CSharpCodeGenerator(_options);

        var solutionId = solutionResolver.ResolveSolutionId(_options.SolutionUniqueName);
        var metadataIds = solutionResolver.GetEntityMetadataIds(solutionId);

        if (metadataIds.Count == 0)
        {
            return new GenerationResult(0, _options.OutputDirectory);
        }

        var entities = await metadataProvider.RetrieveEntitiesAsync(
            metadataIds,
            cancellationToken);

        Directory.CreateDirectory(_options.OutputDirectory);
        var entitiesDirectory = Path.Combine(_options.OutputDirectory, "Entities");
        Directory.CreateDirectory(entitiesDirectory);

        foreach (var entity in entities)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var className = Naming.CSharpIdentifierHelper.ToClassName(entity.LogicalName);
            var filePath = Path.Combine(entitiesDirectory, className + ".cs");
            var source = codeGenerator.GenerateEntityFile(entity);

            await Utf8BomFileWriter.WriteAllTextAsync(filePath, source, cancellationToken);
        }

        var indexPath = Path.Combine(_options.OutputDirectory, "GeneratedAssemblyInfo.cs");
        var indexSource = BuildIndexFile(entities.Count);

        await Utf8BomFileWriter.WriteAllTextAsync(indexPath, indexSource, cancellationToken);

        return new GenerationResult(entities.Count, _options.OutputDirectory);
    }

    private void ValidateOptions()
    {
        if (string.IsNullOrWhiteSpace(_options.ConnectionString))
        {
            throw new InvalidOperationException("Connection string is required.");
        }

        if (string.IsNullOrWhiteSpace(_options.SolutionUniqueName))
        {
            throw new InvalidOperationException("Solution unique name is required.");
        }

        if (string.IsNullOrWhiteSpace(_options.Namespace))
        {
            throw new InvalidOperationException("Namespace is required.");
        }
    }

    private string BuildIndexFile(int entityCount)
    {
        return $@"// <auto-generated />
namespace {_options.Namespace};

/// <summary>
/// Marker for generated CRM types ({entityCount} entities).
/// </summary>
public static class GeneratedModel
{{
    public const string SolutionUniqueName = ""{_options.SolutionUniqueName}"";
    public const int EntityCount = {entityCount};
}}
";
    }
}

public sealed record GenerationResult(int EntityCount, string OutputDirectory);
